from types import SimpleNamespace

from PySide6.QtCore import Qt, QTimer
from PySide6.QtWidgets import (
    QComboBox,
    QDoubleSpinBox,
    QFormLayout,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListView,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QVBoxLayout,
    QWidget,
)


def build_models_page(self, helpers):
    h = SimpleNamespace(**helpers)
    form_label = h.form_label
    ToggleSwitch = h.ToggleSwitch
    FlowLayout = h.FlowLayout
    polish_scroll_area = h.polish_scroll_area

    w = QWidget()
    l = QVBoxLayout(w)
    l.setContentsMargins(40, 40, 40, 40)
    l.setSpacing(0)

    head = QVBoxLayout()
    head.setSpacing(10)
    row = QHBoxLayout()
    pt = QLabel("Models & Workspaces")
    pt.setObjectName("PageTitle")
    row.addWidget(pt)
    row.addStretch()
    refresh_btn = QPushButton("Refresh")
    refresh_btn.setObjectName("ShellBtn")
    refresh_btn.setFixedHeight(34)
    refresh_btn.clicked.connect(self.refresh_ui)
    row.addWidget(refresh_btn)
    head.addLayout(row)

    subtitle = QLabel(
        "Manage the active project profile, export validated model packages from engineering workspaces, "
        "deploy them to the Jetson runtime, and activate the package that the station should use."
    )
    subtitle.setObjectName("PageSubtitle")
    subtitle.setWordWrap(True)
    head.addWidget(subtitle)
    l.addLayout(head)
    l.addSpacing(20)

    def _combo():
        combo = QComboBox()
        combo.setView(QListView())
        combo.setFixedHeight(38)
        combo.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        return combo

    package_grid = QGridLayout()
    package_grid.setHorizontalSpacing(18)
    package_grid.setVerticalSpacing(18)

    export_card = QFrame()
    export_card.setObjectName("InfoCard")
    export_l = QVBoxLayout(export_card)
    export_l.setContentsMargins(24, 22, 24, 22)
    export_l.setSpacing(16)
    export_title = QLabel("Export Package")
    export_title.setObjectName("SectionHeading")
    export_l.addWidget(export_title)
    export_hint = QLabel(
        "Pick a local engineering workspace, select the model artifact and optional labels/runtime files, "
        "then create a versioned package for endpoint deployment."
    )
    export_hint.setObjectName("CaptionMuted")
    export_hint.setWordWrap(True)
    export_l.addWidget(export_hint)

    export_form = QFormLayout()
    export_form.setSpacing(12)
    export_form.setHorizontalSpacing(16)
    self._workspace_export_workspace_combo = _combo()
    self._workspace_export_model_combo = _combo()
    self._workspace_export_labels_combo = _combo()
    self._workspace_export_recipe_combo = _combo()
    self._workspace_export_runtime_combo = _combo()
    self._workspace_export_name_input = QLineEdit()
    self._workspace_export_name_input.setPlaceholderText("vision-inspection-project")
    self._workspace_export_name_input.setMinimumHeight(38)
    self._workspace_export_version_input = QLineEdit(self._package_version_suggestion())
    self._workspace_export_version_input.setPlaceholderText("v2026.04.12.1030")
    self._workspace_export_version_input.setMinimumHeight(38)
    export_form.addRow(form_label("Workspace"), self._workspace_export_workspace_combo)
    export_form.addRow(form_label("Model artifact"), self._workspace_export_model_combo)
    export_form.addRow(form_label("Labels"), self._workspace_export_labels_combo)
    export_form.addRow(form_label("Recipe"), self._workspace_export_recipe_combo)
    export_form.addRow(form_label("Runtime config"), self._workspace_export_runtime_combo)
    export_form.addRow(form_label("Package name"), self._workspace_export_name_input)
    export_form.addRow(form_label("Version"), self._workspace_export_version_input)
    export_l.addLayout(export_form)

    export_actions = QHBoxLayout()
    export_actions.addStretch(1)
    export_btn = QPushButton("Export Package")
    export_btn.setObjectName("BtnPrimary")
    export_btn.setFixedHeight(36)
    export_btn.clicked.connect(self._export_selected_workspace_package)
    export_actions.addWidget(export_btn)
    export_l.addLayout(export_actions)
    package_grid.addWidget(export_card, 0, 0)

    runtime_card = QFrame()
    runtime_card.setObjectName("InfoCard")
    runtime_l = QVBoxLayout(runtime_card)
    runtime_l.setContentsMargins(24, 22, 24, 22)
    runtime_l.setSpacing(16)
    runtime_title = QLabel("Runtime Deployment")
    runtime_title.setObjectName("SectionHeading")
    runtime_l.addWidget(runtime_title)
    self._workspace_package_runtime_label = QLabel("Runtime endpoint: 127.0.0.1:8787")
    self._workspace_package_runtime_label.setObjectName("CaptionMuted")
    self._workspace_package_runtime_label.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
    runtime_l.addWidget(self._workspace_package_runtime_label)
    self._workspace_package_active_label = QLabel("NO ACTIVE PACKAGE")
    self._workspace_package_active_label.setObjectName("StatusPill")
    self._workspace_package_active_label.setProperty("stateTone", "neutral")
    self._workspace_package_active_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    self._workspace_package_active_label.setMinimumHeight(44)
    runtime_l.addWidget(self._workspace_package_active_label)
    self._workspace_package_inventory_label = QLabel("Packages: 0 local / 0 runtime")
    self._workspace_package_inventory_label.setObjectName("CaptionMuted")
    runtime_l.addWidget(self._workspace_package_inventory_label)
    self._workspace_package_status = QLabel("Select a package to deploy or activate.")
    self._workspace_package_status.setObjectName("CaptionMuted")
    self._workspace_package_status.setWordWrap(True)
    runtime_l.addWidget(self._workspace_package_status)

    runtime_form = QFormLayout()
    runtime_form.setSpacing(12)
    runtime_form.setHorizontalSpacing(16)
    self._workspace_local_package_combo = _combo()
    self._workspace_runtime_package_combo = _combo()
    runtime_form.addRow(form_label("Local package"), self._workspace_local_package_combo)
    runtime_form.addRow(form_label("Runtime package"), self._workspace_runtime_package_combo)
    runtime_l.addLayout(runtime_form)

    runtime_actions = QHBoxLayout()
    runtime_actions.setSpacing(10)
    deploy_btn = QPushButton("Deploy to Runtime")
    deploy_btn.setObjectName("BtnSecondary")
    deploy_btn.setFixedHeight(34)
    deploy_btn.clicked.connect(self._deploy_selected_package_to_runtime)
    runtime_actions.addWidget(deploy_btn)
    self._workspace_activate_btn = QPushButton("Activate Package")
    self._workspace_activate_btn.setObjectName("BtnPrimary")
    self._workspace_activate_btn.setFixedHeight(36)
    self._workspace_activate_btn.clicked.connect(self._activate_selected_runtime_package)
    runtime_actions.addWidget(self._workspace_activate_btn)
    self._workspace_rollback_btn = QPushButton("Rollback")
    self._workspace_rollback_btn.setObjectName("BtnSecondary")
    self._workspace_rollback_btn.setFixedHeight(34)
    self._workspace_rollback_btn.clicked.connect(self._rollback_active_runtime_package)
    runtime_actions.addWidget(self._workspace_rollback_btn)
    runtime_actions.addStretch(1)
    runtime_refresh_btn = QPushButton("Refresh Runtime")
    runtime_refresh_btn.setObjectName("ShellBtn")
    runtime_refresh_btn.setFixedHeight(34)
    runtime_refresh_btn.clicked.connect(self._refresh_workspace_package_panel)
    runtime_actions.addWidget(runtime_refresh_btn)
    runtime_l.addLayout(runtime_actions)
    package_grid.addWidget(runtime_card, 0, 1)
    l.addLayout(package_grid)
    self._set_runtime_badge(self._workspace_package_active_label, "NO ACTIVE PACKAGE", "neutral")

    self._workspace_export_workspace_combo.currentIndexChanged.connect(lambda _i: self._refresh_workspace_export_candidates())

    l.addSpacing(22)
    project_profile_card = QFrame()
    project_profile_card.setObjectName("InfoCard")
    project_profile_l = QVBoxLayout(project_profile_card)
    project_profile_l.setContentsMargins(24, 22, 24, 22)
    project_profile_l.setSpacing(16)
    project_profile_title = QLabel("Project Profile")
    project_profile_title.setObjectName("SectionHeading")
    project_profile_l.addWidget(project_profile_title)
    project_profile_hint = QLabel(
        "Keep project recipes, operator-facing pass or fail labels, ROI, and decision thresholds with the model workflow. "
        "Station settings should only contain runtime, camera, and I/O configuration."
    )
    project_profile_hint.setObjectName("CaptionMuted")
    project_profile_hint.setWordWrap(True)
    project_profile_l.addWidget(project_profile_hint)

    def _mk_profile_double(minimum, maximum, decimals=2, step=0.01, value=None, maxw=180):
        s = QDoubleSpinBox()
        s.setRange(minimum, maximum)
        s.setDecimals(decimals)
        s.setSingleStep(step)
        s.setFixedHeight(40)
        s.setMaximumWidth(maxw)
        if value is not None:
            s.setValue(value)
        return s

    self._inspection_profile_name_input = QLineEdit()
    self._inspection_profile_name_input.setPlaceholderText("default_project")
    self._inspection_profile_name_input.setMinimumHeight(40)
    self._inspection_recipe_name_input = QLineEdit()
    self._inspection_recipe_name_input.setPlaceholderText("default_recipe")
    self._inspection_recipe_name_input.setMinimumHeight(40)
    self._inspection_product_label_input = QLineEdit()
    self._inspection_product_label_input.setPlaceholderText("Inspection target")
    self._inspection_product_label_input.setMinimumHeight(40)
    self._inspection_expected_label_input = QLineEdit()
    self._inspection_expected_label_input.setPlaceholderText("target")
    self._inspection_expected_label_input.setMinimumHeight(40)
    self._inspection_pass_display_input = QLineEdit()
    self._inspection_pass_display_input.setPlaceholderText("Pass")
    self._inspection_pass_display_input.setMinimumHeight(40)
    self._inspection_fail_display_input = QLineEdit()
    self._inspection_fail_display_input.setPlaceholderText("Fail")
    self._inspection_fail_display_input.setMinimumHeight(40)
    self._inspection_defect_catalog_input = QLineEdit()
    self._inspection_defect_catalog_input.setPlaceholderText("missing_target, alignment_or_surface_noise, blur_or_out_of_focus")
    self._inspection_defect_catalog_input.setMinimumHeight(40)
    self._inspection_pass_threshold_spin = _mk_profile_double(0.0, 1.0, value=0.35)
    self._inspection_fail_threshold_spin = _mk_profile_double(0.0, 1.0, value=0.65)
    self._inspection_hard_fail_threshold_spin = _mk_profile_double(0.0, 1.0, value=0.9)
    self._inspection_roi_enable_switch = ToggleSwitch()
    self._inspection_roi_x_spin = _mk_profile_double(0.0, 1.0, decimals=3, step=0.01, value=0.0)
    self._inspection_roi_y_spin = _mk_profile_double(0.0, 1.0, decimals=3, step=0.01, value=0.0)
    self._inspection_roi_w_spin = _mk_profile_double(0.0, 1.0, decimals=3, step=0.01, value=1.0)
    self._inspection_roi_h_spin = _mk_profile_double(0.0, 1.0, decimals=3, step=0.01, value=1.0)
    self._inspection_save_fail_switch = ToggleSwitch()
    self._inspection_save_uncertain_switch = ToggleSwitch()

    project_form = QFormLayout()
    project_form.setSpacing(12)
    project_form.setHorizontalSpacing(16)
    project_form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    project_form.addRow(form_label("Profile name"), self._inspection_profile_name_input)
    project_form.addRow(form_label("Recipe name"), self._inspection_recipe_name_input)
    project_form.addRow(form_label("Product label"), self._inspection_product_label_input)
    project_form.addRow(form_label("Expected object"), self._inspection_expected_label_input)
    project_form.addRow(form_label("PASS display label"), self._inspection_pass_display_input)
    project_form.addRow(form_label("FAIL display label"), self._inspection_fail_display_input)
    project_form.addRow(form_label("Defect catalog"), self._inspection_defect_catalog_input)
    project_form.addRow(form_label("PASS threshold"), self._inspection_pass_threshold_spin)
    project_form.addRow(form_label("FAIL threshold"), self._inspection_fail_threshold_spin)
    project_form.addRow(form_label("Hard fail threshold"), self._inspection_hard_fail_threshold_spin)
    roi_enable_cell = QWidget()
    roi_enable_l = QHBoxLayout(roi_enable_cell)
    roi_enable_l.setContentsMargins(0, 0, 0, 0)
    roi_enable_l.addWidget(self._inspection_roi_enable_switch)
    roi_enable_l.addStretch()
    project_form.addRow(form_label("Enable ROI"), roi_enable_cell)
    project_form.addRow(form_label("ROI x"), self._inspection_roi_x_spin)
    project_form.addRow(form_label("ROI y"), self._inspection_roi_y_spin)
    project_form.addRow(form_label("ROI width"), self._inspection_roi_w_spin)
    project_form.addRow(form_label("ROI height"), self._inspection_roi_h_spin)
    save_fail_cell = QWidget()
    save_fail_l = QHBoxLayout(save_fail_cell)
    save_fail_l.setContentsMargins(0, 0, 0, 0)
    save_fail_l.addWidget(self._inspection_save_fail_switch)
    save_fail_l.addStretch()
    project_form.addRow(form_label("Save FAIL images"), save_fail_cell)
    save_uncertain_cell = QWidget()
    save_uncertain_l = QHBoxLayout(save_uncertain_cell)
    save_uncertain_l.setContentsMargins(0, 0, 0, 0)
    save_uncertain_l.addWidget(self._inspection_save_uncertain_switch)
    save_uncertain_l.addStretch()
    project_form.addRow(form_label("Save UNCERTAIN images"), save_uncertain_cell)
    project_profile_l.addLayout(project_form)

    self._inspection_sock_profile_hint = QLabel("")
    self._inspection_sock_profile_hint.setObjectName("CaptionMuted")
    self._inspection_sock_profile_hint.setWordWrap(True)
    project_profile_l.addWidget(self._inspection_sock_profile_hint)

    project_actions = QHBoxLayout()
    project_actions.addStretch(1)
    project_reload_btn = QPushButton("Reload Profile")
    project_reload_btn.setObjectName("BtnSecondary")
    project_reload_btn.setFixedHeight(34)
    project_reload_btn.clicked.connect(self._sync_inspection_profile_ui)
    project_actions.addWidget(project_reload_btn)
    project_profile_l.addLayout(project_actions)
    l.addWidget(project_profile_card)

    self._inspection_profile_name_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_recipe_name_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_product_label_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_expected_label_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_pass_display_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_fail_display_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_defect_catalog_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_pass_threshold_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_fail_threshold_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_hard_fail_threshold_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_roi_enable_switch.toggled.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_roi_x_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_roi_y_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_roi_w_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_roi_h_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_save_fail_switch.toggled.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_save_uncertain_switch.toggled.connect(lambda _v: self._save_inspection_profile_from_ui())

    l.addSpacing(22)
    workspace_head = QVBoxLayout()
    workspace_head.setSpacing(8)
    work_row = QHBoxLayout()
    work_title = QLabel("Engineering Workspaces")
    work_title.setObjectName("SectionHeading")
    work_row.addWidget(work_title)
    work_row.addStretch(1)
    workspace_filter = QLineEdit()
    workspace_filter.setPlaceholderText("Search workspaces")
    workspace_filter.setFixedWidth(260)
    workspace_filter.setMinimumHeight(34)
    workspace_filter.textChanged.connect(self.filter_workspaces)
    work_row.addWidget(workspace_filter)
    workspace_head.addLayout(work_row)
    work_note = QLabel(
        "Use workspaces for training, conversion, testing, and package export for the active inspection project. "
        "Daily operators normally work only with Inspection, Results, and validated runtime packages."
    )
    work_note.setObjectName("CaptionMuted")
    work_note.setWordWrap(True)
    workspace_head.addWidget(work_note)
    l.addLayout(workspace_head)
    l.addSpacing(12)

    workspace_scroll = QScrollArea()
    workspace_scroll.setWidgetResizable(True)
    workspace_container = QWidget()
    self.df = FlowLayout(workspace_container)
    self.df.setContentsMargins(0, 0, 0, 0)
    self.df.setSpacing(20)
    self.abd = self.create_add_btn(
        "New Model Workspace",
        self.modal_doc,
        "Create a development workspace container for model packaging and validation tasks.",
    )
    self.df.addWidget(self.abd)
    workspace_scroll.setWidget(workspace_container)
    polish_scroll_area(workspace_scroll)
    l.addWidget(workspace_scroll, 1)

    QTimer.singleShot(100, self.refresh_ui)
    return w
