import os
import platform
from types import SimpleNamespace

import psutil
from PySide6.QtCore import Qt, QTimer
from PySide6.QtWidgets import (
    QApplication,
    QComboBox,
    QFormLayout,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListView,
    QPushButton,
    QScrollArea,
    QSlider,
    QSpinBox,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)


def build_settings_page(self, helpers):
    h = SimpleNamespace(**helpers)
    settings_title = h.settings_title
    polish_scroll_area = h.polish_scroll_area
    form_label = h.form_label
    form_label_sm = h.form_label_sm
    hairline = h.hairline
    ToggleSwitch = h.ToggleSwitch
    DockerManager = h.DockerManager
    get_zerotier_networks = h.get_zerotier_networks
    get_zerotier_peer_count = h.get_zerotier_peer_count
    get_zerotier_status = h.get_zerotier_status
    get_zerotier_local_ips = h.get_zerotier_local_ips
    get_zerotier_peers = h.get_zerotier_peers
    get_camera_defaults = h.get_camera_defaults
    set_camera_defaults = h.set_camera_defaults
    csi_sensor_default_focuser = h.csi_sensor_default_focuser
    csi_sensor_profiles = h.csi_sensor_profiles
    csi_sensor_recommended_capture = h.csi_sensor_recommended_capture
    csi_sensor_default_resolution_index = h.csi_sensor_default_resolution_index
    focuser_profiles = h.focuser_profiles
    CAMERA_RESOLUTION_PRESETS = h.CAMERA_RESOLUTION_PRESETS
    jetson_board_catalog = h.jetson_board_catalog
    DonutChart = h.DonutChart
    get_gpu_info = h.get_gpu_info
    load_app_prefs = h.load_app_prefs
    make_icon_refresh_button = h.make_icon_refresh_button
    CollapsibleSection = h.CollapsibleSection

    root = QWidget()
    l = QVBoxLayout(root)
    l.setContentsMargins(28, 28, 28, 28)
    l.setSpacing(22)

    overview = QFrame()
    overview.setObjectName("InfoCard")
    overview_l = QVBoxLayout(overview)
    overview_l.setContentsMargins(24, 22, 24, 22)
    overview_l.setSpacing(10)
    overview_title = QLabel("System Settings")
    overview_title.setObjectName("SectionHeading")
    overview_l.addWidget(overview_title)
    overview_hint = QLabel(
        "Keep runtime endpoints, remote access, diagnostics, and maintenance here. "
        "Model packages, recipes, thresholds, and workspace operations live under Models & Workspaces."
    )
    overview_hint.setObjectName("CaptionMuted")
    overview_hint.setWordWrap(True)
    overview_l.addWidget(overview_hint)
    overview_meta = QLabel("Choose the lane you need instead of scrolling through every card.")
    overview_meta.setObjectName("CaptionMuted")
    overview_meta.setWordWrap(True)
    overview_l.addWidget(overview_meta)
    role_row = QHBoxLayout()
    role_lbl = QLabel("Access mode")
    role_lbl.setObjectName("SettingsRowLabel")
    role_row.addWidget(role_lbl)
    self._settings_role_switch = ToggleSwitch()
    self._settings_role_switch.toggled.connect(
        lambda checked: self.set_ui_role_mode("engineering" if checked else "operator")
    )
    role_row.addStretch(1)
    role_row.addWidget(self._settings_role_switch)
    overview_l.addLayout(role_row)
    self._settings_role_hint_label = QLabel("")
    self._settings_role_hint_label.setObjectName("CaptionMuted")
    self._settings_role_hint_label.setWordWrap(True)
    overview_l.addWidget(self._settings_role_hint_label)
    self._settings_lock_hint_label = QLabel("🔒 Locked controls require Engineering mode.")
    self._settings_lock_hint_label.setObjectName("RoleLockHint")
    self._settings_lock_hint_label.setWordWrap(True)
    overview_l.addWidget(self._settings_lock_hint_label)
    fleet_row = QHBoxLayout()
    fleet_row.setSpacing(8)
    self._fleet_runtime_chip = QLabel("Runtime Unchecked")
    self._fleet_runtime_chip.setObjectName("StatusPill")
    self._fleet_nodes_chip = QLabel("1 Endpoint")
    self._fleet_nodes_chip.setObjectName("StatusPill")
    self._fleet_zt_chip = QLabel("ZT UNKNOWN")
    self._fleet_zt_chip.setObjectName("StatusPill")
    fleet_row.addWidget(self._fleet_runtime_chip)
    fleet_row.addWidget(self._fleet_nodes_chip)
    fleet_row.addWidget(self._fleet_zt_chip)
    fleet_row.addStretch(1)
    overview_l.addLayout(fleet_row)

    hub_grid = QGridLayout()
    hub_grid.setContentsMargins(0, 6, 0, 0)
    hub_grid.setHorizontalSpacing(12)
    hub_grid.setVerticalSpacing(12)

    def _make_settings_hub_button(attr_name, tab_index=None, switch_index=None):
        btn = QPushButton("")
        btn.setObjectName("SettingsHubBtn")
        btn.setCursor(Qt.CursorShape.PointingHandCursor)
        btn.setMinimumHeight(84)
        if tab_index is not None:
            btn.clicked.connect(lambda _=False, idx=tab_index: self._select_settings_tab(idx))
        elif switch_index is not None:
            btn.clicked.connect(lambda _=False, idx=switch_index: self.switch(idx))
        setattr(self, attr_name, btn)
        return btn

    self._settings_lock_labels = {}

    def _lockable_form_label(text, lock_key=None):
        lbl = form_label(text)
        lbl.setProperty("baseText", text)
        if lock_key:
            self._settings_lock_labels[lock_key] = lbl
        return lbl

    hub_grid.addWidget(_make_settings_hub_button("_settings_hub_station_btn", tab_index=0), 0, 0)
    hub_grid.addWidget(_make_settings_hub_button("_settings_hub_network_btn", tab_index=1), 0, 1)
    hub_grid.addWidget(_make_settings_hub_button("_settings_hub_system_btn", tab_index=2), 0, 2)
    hub_grid.addWidget(_make_settings_hub_button("_settings_hub_maintenance_btn", tab_index=3), 1, 0)
    hub_grid.addWidget(_make_settings_hub_button("_settings_hub_models_btn", switch_index=2), 1, 1)
    if not getattr(self, "_production_mode", False):
        hub_grid.addWidget(_make_settings_hub_button("_settings_hub_engineering_btn", tab_index=4), 1, 2)
    overview_l.addLayout(hub_grid)
    l.addWidget(overview)

    self._settings_tabs = QTabWidget()
    self._settings_tabs.setObjectName("SettingsTabs")
    self._settings_tabs.setDocumentMode(True)
    self._settings_tabs.setUsesScrollButtons(False)
    self._settings_tabs.setElideMode(Qt.TextElideMode.ElideNone)

    def _make_settings_tab():
        sc = QScrollArea()
        sc.setWidgetResizable(True)
        sc.setStyleSheet("background: transparent; border: none;")
        inner = QWidget()
        inner_l = QVBoxLayout(inner)
        inner_l.setContentsMargins(10, 12, 10, 28)
        inner_l.setSpacing(28)
        sc.setWidget(inner)
        polish_scroll_area(sc)
        return sc, inner_l

    station_tab, station_l = _make_settings_tab()
    network_tab, network_l = _make_settings_tab()
    system_tab, system_l = _make_settings_tab()
    maintenance_tab, maintenance_l = _make_settings_tab()
    engineering_tab = None
    engineering_l = None
    if not getattr(self, "_production_mode", False):
        engineering_tab, engineering_l = _make_settings_tab()

    self._settings_tabs.addTab(station_tab, "Runtime")
    self._settings_tabs.addTab(network_tab, "Remote Access")
    self._settings_tabs.addTab(system_tab, "Diagnostics")
    self._settings_tabs.addTab(maintenance_tab, "Maintenance")
    self._settings_engineering_tab_index = None
    if engineering_tab is not None:
        self._settings_engineering_tab_index = self._settings_tabs.addTab(
            engineering_tab, "Engineering"
        )
    l.addWidget(self._settings_tabs, 1)

    self.node_ip = QLineEdit()
    self.node_ip.hide()
    env_r = (os.getenv("JETSON_REMOTE") or "").strip()
    file_r = (load_app_prefs().get("remote_host_ip") or "").strip()
    self.node_ip.setText(env_r or file_r or "")

    network_l.addWidget(settings_title("Runtime endpoint access"))
    remote_access_card = QFrame()
    remote_access_card.setObjectName("InfoCard")
    remote_access_l = QVBoxLayout(remote_access_card)
    remote_access_l.setContentsMargins(25, 22, 25, 22)
    remote_access_l.setSpacing(14)
    remote_access_title_row = QHBoxLayout()
    remote_access_title = QLabel("Runtime connection")
    remote_access_title.setObjectName("SectionHeading")
    remote_access_title_row.addWidget(remote_access_title)
    remote_access_title_row.addStretch(1)
    self.remote_node_status_label = QLabel("Checking…")
    self.remote_node_status_label.setObjectName("StatusPill")
    self.remote_node_status_label.setProperty("stateTone", "neutral")
    remote_access_title_row.addWidget(self.remote_node_status_label)
    remote_access_l.addLayout(remote_access_title_row)
    remote_access_hint = QLabel(
        "Leave this empty for the primary local runtime, or enter a ZeroTier / LAN endpoint for a remote edge node."
    )
    remote_access_hint.setObjectName("CaptionMuted")
    remote_access_hint.setWordWrap(True)
    remote_access_l.addWidget(remote_access_hint)
    remote_access_form = QFormLayout()
    remote_access_form.setSpacing(12)
    remote_access_form.setHorizontalSpacing(16)
    self.remote_host_input = QLineEdit()
    self.remote_host_input.setPlaceholderText("Local runtime or remote IP")
    self.remote_host_input.setMinimumHeight(40)
    self.remote_host_input.setText(self.node_ip.text())
    self.remote_host_input.textChanged.connect(lambda t: self.node_ip.setText((t or "").strip()))
    self.remote_host_input.textChanged.connect(self._on_remote_host_text_changed)
    remote_access_form.addRow(form_label("Runtime host"), self.remote_host_input)
    remote_access_l.addLayout(remote_access_form)
    self._remote_access_summary_label = QLabel("")
    self._remote_access_summary_label.setObjectName("CaptionMuted")
    self._remote_access_summary_label.setWordWrap(True)
    remote_access_l.addWidget(self._remote_access_summary_label)
    remote_access_actions = QHBoxLayout()
    remote_access_actions.setSpacing(10)
    remote_refresh_btn = QPushButton("Check Connection")
    remote_refresh_btn.setObjectName("BtnSecondary")
    remote_refresh_btn.setFixedHeight(34)
    remote_refresh_btn.clicked.connect(lambda: self._schedule_remote_status_check(force=True))
    remote_access_actions.addWidget(remote_refresh_btn)
    remote_devices_btn = QPushButton("Open Devices")
    remote_devices_btn.setObjectName("ShellBtn")
    remote_devices_btn.setFixedHeight(34)
    remote_devices_btn.clicked.connect(lambda: self.switch(3))
    remote_access_actions.addWidget(remote_devices_btn)
    remote_access_actions.addStretch(1)
    remote_access_l.addLayout(remote_access_actions)
    network_l.addWidget(remote_access_card)

    network_l.addWidget(settings_title("ZeroTier management"))
    zt_mgmt_card = QFrame()
    zt_mgmt_card.setObjectName("InfoCard")
    ztm_l = QVBoxLayout(zt_mgmt_card)
    ztm_l.setContentsMargins(25, 20, 25, 20)
    ztm_l.setSpacing(12)
    ztm_title = QLabel("Join / Leave a ZeroTier network")
    ztm_title.setObjectName("SectionHeading")
    ztm_l.addWidget(ztm_title)
    ztm_hint = QLabel(
        "Enter a 16-character Network ID and click Join. "
        "The device must be Authorized in ZeroTier Central before traffic flows."
    )
    ztm_hint.setObjectName("CaptionMuted")
    ztm_hint.setWordWrap(True)
    ztm_l.addWidget(ztm_hint)
    ztm_row = QHBoxLayout()
    ztm_row.setSpacing(8)
    self._zt_nwid_input = QLineEdit()
    self._zt_nwid_input.setPlaceholderText("Network ID  (e.g. 8056c2e21c000001)")
    self._zt_nwid_input.setMaxLength(16)
    self._zt_nwid_input.setObjectName("SettingsInput")
    self._zt_nwid_input.setFixedHeight(34)
    self._zt_nwid_input.setToolTip(
        "16-character ZeroTier Network ID.\n"
        "Find it at: my.zerotier.com → Networks → your network."
    )
    ztm_row.addWidget(self._zt_nwid_input, 1)
    self._zt_join_btn = QPushButton("Join")
    self._zt_join_btn.setObjectName("PrimaryBtn")
    self._zt_join_btn.setFixedHeight(34)
    self._zt_join_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self._zt_join_btn.clicked.connect(self._zt_join_network)
    ztm_row.addWidget(self._zt_join_btn)
    self._zt_leave_btn = QPushButton("Leave")
    self._zt_leave_btn.setObjectName("DangerBtn")
    self._zt_leave_btn.setFixedHeight(34)
    self._zt_leave_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self._zt_leave_btn.clicked.connect(self._zt_leave_network)
    ztm_row.addWidget(self._zt_leave_btn)
    ztm_l.addLayout(ztm_row)
    _zt_central_lbl = QLabel('<a href="https://my.zerotier.com">Open ZeroTier Central ↗</a>')
    _zt_central_lbl.setObjectName("CaptionMuted")
    _zt_central_lbl.setOpenExternalLinks(True)
    ztm_l.addWidget(_zt_central_lbl)
    network_l.addWidget(zt_mgmt_card)

    maintenance_l.addWidget(settings_title("Maintenance essentials"))
    maintenance_card = QFrame()
    maintenance_card.setObjectName("InfoCard")
    maintenance_card_l = QVBoxLayout(maintenance_card)
    maintenance_card_l.setContentsMargins(25, 22, 25, 22)
    maintenance_card_l.setSpacing(14)
    maintenance_title = QLabel("Backup and preferences")
    maintenance_title.setObjectName("SectionHeading")
    maintenance_card_l.addWidget(maintenance_title)
    maintenance_hint = QLabel(
        "Keep backup, operator preferences, and light cleanup actions together. "
        "Advanced image repository controls are moved to Engineering."
    )
    maintenance_hint.setObjectName("CaptionMuted")
    maintenance_hint.setWordWrap(True)
    maintenance_card_l.addWidget(maintenance_hint)
    self._maintenance_snapshot_label = QLabel("")
    self._maintenance_snapshot_label.setObjectName("CaptionMuted")
    self._maintenance_snapshot_label.setWordWrap(True)
    maintenance_card_l.addWidget(self._maintenance_snapshot_label)
    maintenance_actions = QHBoxLayout()
    maintenance_actions.setSpacing(10)
    self._maintenance_export_btn = QPushButton("Export Settings")
    self._maintenance_export_btn.setObjectName("BtnSecondary")
    self._maintenance_export_btn.setFixedHeight(32)
    self._maintenance_export_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self._maintenance_export_btn.clicked.connect(self.export_settings_json)
    self._maintenance_import_btn = QPushButton("Import Settings")
    self._maintenance_import_btn.setObjectName("BtnSecondary")
    self._maintenance_import_btn.setFixedHeight(32)
    self._maintenance_import_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self._maintenance_import_btn.clicked.connect(self.import_settings_json)
    self._maintenance_setup_btn = QPushButton("Open Production Setup")
    self._maintenance_setup_btn.setObjectName("BtnSecondary")
    self._maintenance_setup_btn.setFixedHeight(32)
    self._maintenance_setup_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self._maintenance_setup_btn.clicked.connect(lambda: self._show_onboarding_wizard(force=True))
    maintenance_actions.addWidget(self._maintenance_export_btn)
    maintenance_actions.addWidget(self._maintenance_import_btn)
    maintenance_actions.addWidget(self._maintenance_setup_btn)
    maintenance_actions.addStretch()
    maintenance_card_l.addLayout(maintenance_actions)

    pref_card = QFrame()
    pref_card.setObjectName("SettingsSummaryCard")
    pref_l = QVBoxLayout(pref_card)
    pref_l.setContentsMargins(18, 16, 18, 16)
    pref_l.setSpacing(14)
    safe_hint = QLabel("Safe defaults are always-available controls for day-to-day operation.")
    safe_hint.setObjectName("CaptionMuted")
    safe_hint.setWordWrap(True)
    pref_l.addWidget(safe_hint)
    dh = QHBoxLayout()
    eco_l = QLabel("Eco mode (thermal guard)")
    eco_l.setObjectName("SettingsRowLabel")
    dh.addWidget(eco_l)
    self._maintenance_eco_switch = ToggleSwitch()
    self._maintenance_eco_switch.toggled.connect(self.toggle_eco)
    dh.addStretch()
    dh.addWidget(self._maintenance_eco_switch)
    pref_l.addLayout(dh)
    ph = QHBoxLayout()
    dark_l = QLabel("Dark theme")
    dark_l.setObjectName("SettingsRowLabel")
    ph.addWidget(dark_l)
    self._maintenance_theme_switch = ToggleSwitch()
    self._maintenance_theme_switch.toggled.connect(self.toggle_theme)
    ph.addStretch()
    ph.addWidget(self._maintenance_theme_switch)
    pref_l.addLayout(ph)
    advanced = CollapsibleSection("Advanced controls", is_collapsed=True)
    self._settings_advanced_section = advanced
    scheduler_row = QHBoxLayout()
    scheduler_lbl = QLabel("Automation profile")
    scheduler_lbl.setObjectName("SettingsRowLabel")
    scheduler_row.addWidget(scheduler_lbl)
    self._maintenance_scheduler_profile_combo = QComboBox()
    self._maintenance_scheduler_profile_combo.setView(QListView())
    self._maintenance_scheduler_profile_combo.setFixedHeight(36)
    self._maintenance_scheduler_profile_combo.setMaximumWidth(240)
    self._maintenance_scheduler_profile_combo.addItem("Manual (recommended)", "manual")
    self._maintenance_scheduler_profile_combo.addItem("Balanced", "balanced")
    self._maintenance_scheduler_profile_combo.addItem("Full automation", "full")
    self._maintenance_scheduler_profile_combo.addItem("Custom", "custom")
    self._maintenance_scheduler_profile_combo.currentIndexChanged.connect(
        lambda _i: (
            self.set_scheduler_profile(self._maintenance_scheduler_profile_combo.currentData())
            if self._maintenance_scheduler_profile_combo.currentData() != "custom"
            else None
        )
    )
    scheduler_row.addStretch()
    scheduler_row.addWidget(self._maintenance_scheduler_profile_combo)
    advanced.addLayout(scheduler_row)
    self._maintenance_scheduler_summary_label = QLabel("")
    self._maintenance_scheduler_summary_label.setObjectName("CaptionMuted")
    self._maintenance_scheduler_summary_label.setWordWrap(True)
    advanced.addWidget(self._maintenance_scheduler_summary_label)
    adv_hint = QLabel(
        "Use these only when you explicitly want background automation. "
        "Disabled values keep runtime checks and camera scans fully manual."
    )
    adv_hint.setObjectName("CaptionMuted")
    adv_hint.setWordWrap(True)
    advanced.addWidget(adv_hint)
    bg_row = QHBoxLayout()
    bg_l = QLabel("Background runtime checks")
    bg_l.setObjectName("SettingsRowLabel")
    bg_row.addWidget(bg_l)
    self._maintenance_bg_checks_switch = ToggleSwitch()
    self._maintenance_bg_checks_switch.toggled.connect(self.toggle_background_health_checks)
    bg_row.addStretch()
    bg_row.addWidget(self._maintenance_bg_checks_switch)
    advanced.addLayout(bg_row)
    auto_row = QHBoxLayout()
    auto_l = QLabel("Auto-start camera previews on launch")
    auto_l.setObjectName("SettingsRowLabel")
    auto_row.addWidget(auto_l)
    self._maintenance_camera_autostart_switch = ToggleSwitch()
    self._maintenance_camera_autostart_switch.toggled.connect(self.toggle_camera_preview_autostart)
    auto_row.addStretch()
    auto_row.addWidget(self._maintenance_camera_autostart_switch)
    advanced.addLayout(auto_row)
    setopen_row = QHBoxLayout()
    setopen_l = QLabel("Check remote status when opening Settings")
    setopen_l.setObjectName("SettingsRowLabel")
    setopen_row.addWidget(setopen_l)
    self._maintenance_check_on_settings_open_switch = ToggleSwitch()
    self._maintenance_check_on_settings_open_switch.toggled.connect(self.toggle_remote_check_on_settings_open)
    setopen_row.addStretch()
    setopen_row.addWidget(self._maintenance_check_on_settings_open_switch)
    advanced.addLayout(setopen_row)
    setupwiz_row = QHBoxLayout()
    setupwiz_l = QLabel("Show Production Setup on app launch")
    setupwiz_l.setObjectName("SettingsRowLabel")
    setupwiz_row.addWidget(setupwiz_l)
    self._maintenance_setup_wizard_on_launch_switch = ToggleSwitch()
    self._maintenance_setup_wizard_on_launch_switch.toggled.connect(self.toggle_setup_wizard_on_launch)
    setupwiz_row.addStretch()
    setupwiz_row.addWidget(self._maintenance_setup_wizard_on_launch_switch)
    advanced.addLayout(setupwiz_row)
    devrefresh_row = QHBoxLayout()
    devrefresh_l = QLabel("Auto-refresh Devices page (every minute)")
    devrefresh_l.setObjectName("SettingsRowLabel")
    devrefresh_row.addWidget(devrefresh_l)
    self._maintenance_devices_auto_refresh_switch = ToggleSwitch()
    self._maintenance_devices_auto_refresh_switch.toggled.connect(self.toggle_devices_auto_refresh)
    self._maintenance_devices_auto_refresh_interval_combo = QComboBox()
    self._maintenance_devices_auto_refresh_interval_combo.setView(QListView())
    self._maintenance_devices_auto_refresh_interval_combo.setFixedHeight(34)
    self._maintenance_devices_auto_refresh_interval_combo.setMaximumWidth(136)
    self._maintenance_devices_auto_refresh_interval_combo.addItem("30 sec", 30)
    self._maintenance_devices_auto_refresh_interval_combo.addItem("60 sec", 60)
    self._maintenance_devices_auto_refresh_interval_combo.addItem("120 sec", 120)
    self._maintenance_devices_auto_refresh_interval_combo.currentIndexChanged.connect(
        lambda _i: self.set_devices_auto_refresh_interval(
            int(self._maintenance_devices_auto_refresh_interval_combo.currentData() or 60)
        )
    )
    devrefresh_row.addStretch()
    devrefresh_row.addWidget(self._maintenance_devices_auto_refresh_interval_combo)
    devrefresh_row.addWidget(self._maintenance_devices_auto_refresh_switch)
    advanced.addLayout(devrefresh_row)
    pref_l.addWidget(advanced)
    self._maintenance_eco_switch.blockSignals(True)
    self._maintenance_eco_switch.setChecked(bool(getattr(self, "eco_mode", False)))
    self._maintenance_eco_switch.blockSignals(False)
    self._maintenance_theme_switch.blockSignals(True)
    self._maintenance_theme_switch.setChecked(bool(getattr(self, "is_dark", True)))
    self._maintenance_theme_switch.blockSignals(False)
    self._maintenance_bg_checks_switch.blockSignals(True)
    self._maintenance_bg_checks_switch.setChecked(bool(getattr(self, "_background_health_checks_enabled", False)))
    self._maintenance_bg_checks_switch.blockSignals(False)
    self._maintenance_camera_autostart_switch.blockSignals(True)
    self._maintenance_camera_autostart_switch.setChecked(bool(getattr(self, "_auto_camera_preview_on_launch", False)))
    self._maintenance_camera_autostart_switch.blockSignals(False)
    self._maintenance_check_on_settings_open_switch.blockSignals(True)
    self._maintenance_check_on_settings_open_switch.setChecked(bool(getattr(self, "_check_remote_on_settings_open", False)))
    self._maintenance_check_on_settings_open_switch.blockSignals(False)
    self._maintenance_setup_wizard_on_launch_switch.blockSignals(True)
    self._maintenance_setup_wizard_on_launch_switch.setChecked(bool(getattr(self, "_show_setup_wizard_on_launch", False)))
    self._maintenance_setup_wizard_on_launch_switch.blockSignals(False)
    self._maintenance_devices_auto_refresh_switch.blockSignals(True)
    self._maintenance_devices_auto_refresh_switch.setChecked(bool(getattr(self, "_devices_auto_refresh_enabled", False)))
    self._maintenance_devices_auto_refresh_switch.blockSignals(False)
    self._maintenance_devices_auto_refresh_interval_combo.blockSignals(True)
    _interval_target = int(getattr(self, "_devices_auto_refresh_interval_sec", 60) or 60)
    _interval_idx = self._maintenance_devices_auto_refresh_interval_combo.findData(_interval_target)
    if _interval_idx < 0:
        _interval_idx = self._maintenance_devices_auto_refresh_interval_combo.findData(60)
    if _interval_idx >= 0:
        self._maintenance_devices_auto_refresh_interval_combo.setCurrentIndex(_interval_idx)
    self._maintenance_devices_auto_refresh_interval_combo.blockSignals(False)
    maintenance_card_l.addWidget(pref_card)
    maintenance_l.addWidget(maintenance_card)

    notif_card = QFrame()
    notif_card.setObjectName("InfoCard")
    ncl = QVBoxLayout(notif_card)
    ncl.setContentsMargins(25, 20, 25, 20)
    ncl.setSpacing(10)
    ntitle = QLabel("Recent notifications")
    ntitle.setObjectName("SectionHeading")
    ncl.addWidget(ntitle)
    self._notif_summary_label = QLabel("")
    self._notif_summary_label.setObjectName("CaptionMuted")
    self._notif_summary_label.setWordWrap(True)
    ncl.addWidget(self._notif_summary_label)
    self._notif_list_box = QVBoxLayout()
    self._notif_list_box.setSpacing(6)
    ncl.addLayout(self._notif_list_box)
    nrow = QHBoxLayout()
    nclear = QPushButton("Clear")
    nclear.setObjectName("BtnSecondary")
    nclear.setFixedHeight(28)
    nclear.setCursor(Qt.CursorShape.PointingHandCursor)
    nclear.clicked.connect(lambda: [setattr(self, "_notifications", []), self._refresh_notifications_panel()])
    nrow.addWidget(nclear)
    nrow.addStretch()
    ncl.addLayout(nrow)
    maintenance_l.addWidget(settings_title("Notifications"))
    maintenance_l.addWidget(notif_card)
    self._refresh_notifications_panel()

    sys_info = QFrame()
    sys_info.setObjectName("InfoCard")
    sl_info = QVBoxLayout(sys_info)
    sl_info.setContentsMargins(25, 25, 25, 25)
    sl_info.setSpacing(15)

    def add_status(lbl, val):
        row = QHBoxLayout()
        row.setSpacing(24)
        ll = QLabel(lbl)
        ll.setObjectName("FormLabel")
        ll.setMinimumWidth(160)
        row.addWidget(ll)
        vl = QLabel(val)
        vl.setObjectName("StateValueLabel")
        row.addWidget(vl)
        row.addStretch()
        sl_info.addLayout(row)

    _docker_running = DockerManager.is_running()
    _docker_row = QHBoxLayout()
    _docker_row.setSpacing(24)
    _docker_lbl = QLabel("Docker engine")
    _docker_lbl.setObjectName("FormLabel")
    _docker_lbl.setMinimumWidth(160)
    _docker_row.addWidget(_docker_lbl)
    self._docker_status_lbl = QLabel("ACTIVE" if _docker_running else "OFFLINE")
    self._docker_status_lbl.setObjectName("StatusPill")
    self._docker_status_lbl.setProperty("stateTone", "success" if _docker_running else "danger")
    _docker_row.addWidget(self._docker_status_lbl)
    self._docker_start_btn = QPushButton("Start Docker")
    self._docker_start_btn.setObjectName("BtnSecondary")
    self._docker_start_btn.setFixedHeight(28)
    self._docker_start_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self._docker_start_btn.setVisible(not _docker_running)
    self._docker_start_btn.clicked.connect(lambda: [DockerManager.start_service(), self.show_toast("Starting Docker…"), QTimer.singleShot(4500, self._refresh_docker_status)])
    _docker_row.addWidget(self._docker_start_btn)
    _docker_row.addStretch()
    sl_info.addLayout(_docker_row)
    add_status("Platform", f"{platform.system()} {platform.machine()}")

    system_l.addWidget(settings_title("Health snapshot"))
    diagnostics_card = QFrame()
    diagnostics_card.setObjectName("InfoCard")
    diagnostics_l = QVBoxLayout(diagnostics_card)
    diagnostics_l.setContentsMargins(25, 22, 25, 22)
    diagnostics_l.setSpacing(12)
    diagnostics_title = QLabel("System overview")
    diagnostics_title.setObjectName("SectionHeading")
    diagnostics_l.addWidget(diagnostics_title)
    diagnostics_hint = QLabel(
        "Use this area for a quick status read. Hardware details and live metrics remain below for maintenance work."
    )
    diagnostics_hint.setObjectName("CaptionMuted")
    diagnostics_hint.setWordWrap(True)
    diagnostics_l.addWidget(diagnostics_hint)
    self._diagnostics_snapshot_label = QLabel("")
    self._diagnostics_snapshot_label.setObjectName("CaptionMuted")
    self._diagnostics_snapshot_label.setWordWrap(True)
    diagnostics_l.addWidget(self._diagnostics_snapshot_label)
    diagnostics_actions = QHBoxLayout()
    diagnostics_actions.setSpacing(10)
    health_btn = QPushButton("Run Health Check")
    health_btn.setObjectName("BtnSecondary")
    health_btn.setFixedHeight(34)
    health_btn.clicked.connect(self.run_health_check)
    diagnostics_actions.addWidget(health_btn)
    refresh_diag_btn = QPushButton("Refresh Diagnostics")
    refresh_diag_btn.setObjectName("ShellBtn")
    refresh_diag_btn.setFixedHeight(34)
    refresh_diag_btn.clicked.connect(self.refresh_settings_page)
    diagnostics_actions.addWidget(refresh_diag_btn)
    diagnostics_actions.addStretch(1)
    diagnostics_l.addLayout(diagnostics_actions)
    system_l.addWidget(diagnostics_card)

    zt_networks = get_zerotier_networks()
    peer_count = get_zerotier_peer_count()
    zt_status = get_zerotier_status()
    zt_local_ips = get_zerotier_local_ips()
    if zt_networks or peer_count is not None or zt_status != "NOT INSTALLED":
        network_l.addWidget(hairline())
        zt_panel = QFrame()
        zt_panel.setObjectName("NetworkInset")
        zt_inner = QVBoxLayout(zt_panel)
        zt_inner.setContentsMargins(16, 16, 16, 16)
        zt_inner.setSpacing(14)
        zt_hdr = QHBoxLayout()
        net_label = QLabel("ZeroTier networks")
        net_label.setObjectName("NetworkPanelHeading")
        zt_hdr.addWidget(net_label)
        zt_hdr.addStretch(1)
        _status_color = {"ONLINE": "#30D158", "OFFLINE": "#FF453A", "NOT INSTALLED": "#8E8E93", "UNKNOWN": "#FF9F0A"}.get(zt_status, "#8E8E93")
        status_dot = QLabel(f"\u25cf {zt_status}")
        status_dot.setObjectName("ZtStatusDot")
        status_dot.setStyleSheet(f"color: {_status_color};")
        zt_hdr.addWidget(status_dot)
        zt_inner.addLayout(zt_hdr)
        if zt_local_ips:
            local_ip_row = QHBoxLayout()
            local_ip_lbl = QLabel("Your ZeroTier IP:")
            local_ip_lbl.setObjectName("FormLabelSm")
            local_ip_row.addWidget(local_ip_lbl)
            local_ip_val = QLabel("  ".join(zt_local_ips))
            local_ip_val.setObjectName("MonoIp")
            local_ip_val.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
            local_ip_row.addWidget(local_ip_val)
            local_ip_row.addStretch(1)
            _copy_lip_btn = QPushButton("Copy")
            _copy_lip_btn.setObjectName("BtnSecondary")
            _copy_lip_btn.setFixedHeight(24)
            _copy_lip_btn.setCursor(Qt.CursorShape.PointingHandCursor)
            _copy_lip_btn.clicked.connect(lambda _, ips=zt_local_ips: [QApplication.clipboard().setText(ips[0]), self.show_toast(f"Copied: {ips[0]}")])
            local_ip_row.addWidget(_copy_lip_btn)
            zt_inner.addLayout(local_ip_row)
        if zt_networks:
            for net in zt_networks:
                nwid = net.get("nwid") or net.get("id") or "—"
                name = net.get("name") or nwid[:16]
                status = net.get("status") or "—"
                addrs = net.get("assignedAddresses") or []
                if not isinstance(addrs, list):
                    addrs = [addrs] if addrs else []
                ip_str = ", ".join(str(a) for a in addrs[:5]) if addrs else "—"
                row = QFrame()
                row.setObjectName("ZerotierNetRow")
                rl = QVBoxLayout(row)
                rl.setContentsMargins(14, 12, 14, 12)
                rl.setSpacing(6)
                nm = QLabel(name)
                nm.setObjectName("ZtNetTitle")
                rl.addWidget(nm)
                subl = QLabel(f"IP: {ip_str}  ·  {status}")
                subl.setObjectName("ZtNetDetail")
                rl.addWidget(subl)
                zt_inner.addWidget(row)
        else:
            nn = QLabel("No networks joined.")
            nn.setObjectName("CaptionMuted")
            zt_inner.addWidget(nn)
        dev_row = QHBoxLayout()
        pv = QLabel("Peers visible:")
        pv.setObjectName("FormLabelSm")
        dev_row.addWidget(pv)
        dev_row.addStretch()
        pc = QLabel(str(peer_count))
        _ac = "#3B82F6" if getattr(self, "is_dark", True) else "#2563EB"
        pc.setStyleSheet(f"font-size: 15px; font-weight: 800; color: {_ac}; border: none;")
        dev_row.addWidget(pc)
        zt_inner.addLayout(dev_row)
        peers_list = get_zerotier_peers()
        if peers_list and not getattr(self, "_production_mode", False):
            default_ssh_user = os.getenv("ZEROTIER_SSH_USER", "jetson")
            peer_hdr = QLabel("Connected devices (copy IP or SSH)")
            peer_hdr.setObjectName("NetworkPanelHeading")
            peer_hdr.setStyleSheet("padding-top: 4px;")
            zt_inner.addWidget(peer_hdr)
            for pr in peers_list:
                role_badge = pr.get("role", "—")
                addr = pr.get("address", "—")
                lat = pr.get("latency") or 0
                peer_ip = (pr.get("ip") or "").strip()
                peer_row = QFrame()
                peer_row.setObjectName("PeerListRow")
                prl = QHBoxLayout(peer_row)
                prl.setContentsMargins(14, 10, 14, 10)
                prl.setSpacing(12)
                dot = QLabel()
                dot.setObjectName("PeerStatusDotOn" if pr.get("connected") else "PeerStatusDotOff")
                prl.addWidget(dot, alignment=Qt.AlignmentFlag.AlignVCenter)
                id_l = QLabel(addr)
                id_l.setObjectName("PeerIdLabel")
                prl.addWidget(id_l, alignment=Qt.AlignmentFlag.AlignVCenter)
                role_l = QLabel(role_badge)
                role_l.setObjectName("PeerRoleLabel")
                prl.addWidget(role_l, alignment=Qt.AlignmentFlag.AlignVCenter)
                ip_l = QLabel(peer_ip or "—")
                ip_l.setObjectName("PeerIpLabel")
                prl.addWidget(ip_l, alignment=Qt.AlignmentFlag.AlignVCenter)
                lat_l = QLabel(f"{lat} ms")
                lat_l.setObjectName("PeerLatencyLabel")
                prl.addWidget(lat_l, alignment=Qt.AlignmentFlag.AlignVCenter)
                prl.addStretch()
                if peer_ip and role_badge == "LEAF":
                    ssh_cmd = f"ssh {default_ssh_user}@{peer_ip}"
                    copy_btn = QPushButton("Copy SSH")
                    copy_btn.setObjectName("BtnSecondary")
                    copy_btn.setFixedHeight(30)
                    copy_btn.setMinimumWidth(88)
                    copy_btn.setCursor(Qt.CursorShape.PointingHandCursor)
                    copy_btn.setToolTip(ssh_cmd)

                    def _copy_ssh(cmd=ssh_cmd):
                        QApplication.clipboard().setText(cmd)
                        app = self.window()
                        if app and hasattr(app, "show_toast"):
                            app.show_toast("SSH command copied")

                    copy_btn.clicked.connect(_copy_ssh)
                    prl.addWidget(copy_btn, alignment=Qt.AlignmentFlag.AlignVCenter)
                    zt_fetch = QPushButton("ZT IP Al")
                    zt_fetch.setObjectName("BtnSecondary")
                    zt_fetch.setFixedHeight(30)
                    zt_fetch.setMinimumWidth(88)
                    zt_fetch.setCursor(Qt.CursorShape.PointingHandCursor)
                    zt_fetch.setToolTip(
                        "Runs zerotier-cli over SSH using the path IP; discovered virtual IP is shown in Devices."
                    )
                    zt_fetch.clicked.connect(
                        lambda _v=False, pip=peer_ip, aid=addr: self._fetch_peer_zt_virtual_ips(
                            pip, default_ssh_user, aid, goto_devices=True
                        )
                    )
                    prl.addWidget(zt_fetch, alignment=Qt.AlignmentFlag.AlignVCenter)
                zt_inner.addWidget(peer_row)
            leaf_hint = QLabel(
                "LEAF = edge device. 'Copy SSH' copies ssh user@IP (default user: jetson; override with ZEROTIER_SSH_USER)."
            )
            leaf_hint.setObjectName("CaptionMuted")
            leaf_hint.setStyleSheet("font-size: 11px; font-weight: 600; padding-top: 4px;")
            zt_inner.addWidget(leaf_hint)
        elif peers_list:
            compact_hint = QLabel(
                "Detailed peer inventory is hidden in production mode. Use Devices for the full remote device list and SSH actions."
            )
            compact_hint.setObjectName("CaptionMuted")
            compact_hint.setWordWrap(True)
            zt_inner.addWidget(compact_hint)
            compact_row = QHBoxLayout()
            compact_btn = QPushButton("Open Devices")
            compact_btn.setObjectName("BtnSecondary")
            compact_btn.setFixedHeight(32)
            compact_btn.clicked.connect(lambda: self.switch(3))
            compact_row.addWidget(compact_btn)
            compact_row.addStretch(1)
            zt_inner.addLayout(compact_row)
        network_l.addWidget(settings_title("Connected ZeroTier devices"))
        network_l.addWidget(zt_panel)

    if engineering_l is not None:
        engineering_l.addWidget(settings_title("Camera commissioning defaults"))
    cam_row = QHBoxLayout()
    cam_row.addStretch(1)
    cam_def = QFrame()
    cam_def.setObjectName("InfoCard")
    cam_def.setMaximumWidth(640)
    cdl = QVBoxLayout(cam_def)
    cdl.setContentsMargins(25, 25, 25, 25)
    cdl.setSpacing(16)
    defs = get_camera_defaults()
    current_sensor_model = str(defs.get("sensor_model") or "GENERIC_CSI").strip().upper()
    current_focuser = str(defs.get("focuser_type") or csi_sensor_default_focuser(current_sensor_model)).strip().lower()
    cam_form = QFormLayout()
    cam_form.setSpacing(14)
    cam_form.setHorizontalSpacing(16)
    cam_form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    cam_form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    self.camera_sensor_model_combo = QComboBox()
    self.camera_sensor_model_combo.setView(QListView())
    self.camera_sensor_model_combo.setFixedHeight(40)
    self.camera_sensor_model_combo.setMaximumWidth(300)
    for key, info in csi_sensor_profiles().items():
        self.camera_sensor_model_combo.addItem(info.get("label") or key, key)
    sensor_idx = 0
    for i in range(self.camera_sensor_model_combo.count()):
        if self.camera_sensor_model_combo.itemData(i) == current_sensor_model:
            sensor_idx = i
            break
    self.camera_sensor_model_combo.setCurrentIndex(sensor_idx)
    self.camera_sensor_model_combo.currentIndexChanged.connect(self._on_camera_sensor_model_changed)
    cam_form.addRow(form_label("CSI sensor family"), self.camera_sensor_model_combo)
    self.camera_focuser_combo = QComboBox()
    self.camera_focuser_combo.setView(QListView())
    self.camera_focuser_combo.setFixedHeight(40)
    self.camera_focuser_combo.setMaximumWidth(320)
    for key, info in focuser_profiles().items():
        self.camera_focuser_combo.addItem(info.get("label") or key, key)
    focuser_idx = 0
    for i in range(self.camera_focuser_combo.count()):
        if self.camera_focuser_combo.itemData(i) == current_focuser:
            focuser_idx = i
            break
    self.camera_focuser_combo.setCurrentIndex(focuser_idx)
    self.camera_focuser_combo.currentIndexChanged.connect(
        lambda: [set_camera_defaults(focuser_type=self.camera_focuser_combo.currentData()), self._refresh_camera_sensor_profile_hint()]
    )
    cam_form.addRow(form_label("Focus actuator"), self.camera_focuser_combo)
    self.camera_res_combo = QComboBox()
    self.camera_res_combo.setView(QListView())
    self.camera_res_combo.setFixedHeight(40)
    self.camera_res_combo.setMaximumWidth(250)
    for i, preset in enumerate(CAMERA_RESOLUTION_PRESETS):
        self.camera_res_combo.addItem(preset[0], i)
    self.camera_res_combo.setCurrentIndex(min(defs["resolution_index"], self.camera_res_combo.count() - 1))
    self.camera_res_combo.currentIndexChanged.connect(lambda i: set_camera_defaults(resolution_index=i))
    cam_form.addRow(form_label("Resolution"), self.camera_res_combo)
    aelock_cell = QWidget()
    ael_h = QHBoxLayout(aelock_cell)
    ael_h.setContentsMargins(0, 0, 0, 0)
    self.camera_aelock_switch = ToggleSwitch()
    self.camera_aelock_switch.setChecked(defs.get("aelock", False))
    self.camera_aelock_switch.toggled.connect(lambda c: [set_camera_defaults(aelock=c), self._update_aelock_sliders_visibility()])
    ael_h.addWidget(self.camera_aelock_switch)
    ael_h.addStretch()
    cam_form.addRow(form_label("AE lock (manual exposure)"), aelock_cell)
    cdl.addLayout(cam_form)

    self.camera_exp_block = QWidget()
    ev = QVBoxLayout(self.camera_exp_block)
    ev.setContentsMargins(0, 0, 0, 0)
    ev.setSpacing(10)
    ev.addWidget(form_label_sm("Exposure (when AE lock is on)"))
    self.camera_exposure_slider = QSlider(Qt.Orientation.Horizontal)
    self.camera_exposure_slider.setRange(100, 100000)
    self.camera_exposure_slider.setValue(defs.get("v4l2_exposure", 5000))
    self.camera_exposure_slider.setTickPosition(QSlider.TickPosition.TicksBelow)
    self.camera_exposure_slider.setTickInterval(10000)
    self.camera_exposure_slider.valueChanged.connect(lambda v: [set_camera_defaults(v4l2_exposure=v), self._apply_v4l2_exposure_gain()])
    ev.addWidget(self.camera_exposure_slider)
    ev.addWidget(form_label_sm("Gain (when AE lock is on)"))
    self.camera_gain_slider = QSlider(Qt.Orientation.Horizontal)
    self.camera_gain_slider.setRange(1, 200)
    self.camera_gain_slider.setValue(defs.get("v4l2_gain", 16))
    self.camera_gain_slider.valueChanged.connect(lambda v: [set_camera_defaults(v4l2_gain=v), self._apply_v4l2_exposure_gain()])
    ev.addWidget(self.camera_gain_slider)
    exp_hint = QLabel("Applies to /dev/video0 when AE lock is on. Restart the stream after changing AE lock.")
    exp_hint.setObjectName("CaptionMuted")
    exp_hint.setWordWrap(True)
    ev.addWidget(exp_hint)
    cdl.addWidget(self.camera_exp_block)

    cdl.addWidget(hairline())
    cam_form2 = QFormLayout()
    cam_form2.setSpacing(14)
    cam_form2.setHorizontalSpacing(16)
    cam_form2.setLabelAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    cam_form2.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    self.camera_i2c_spin = QSpinBox()
    self.camera_i2c_spin.setRange(0, 15)
    self.camera_i2c_spin.setValue(int(defs.get("i2c_bus", 10)))
    self.camera_i2c_spin.valueChanged.connect(lambda v: set_camera_defaults(i2c_bus=v))
    i2c_cell = QWidget()
    i2c_h = QHBoxLayout(i2c_cell)
    i2c_h.setContentsMargins(0, 0, 0, 0)
    i2c_h.addWidget(self.camera_i2c_spin)
    i2c_h.addStretch()
    cam_form2.addRow(form_label("I2C bus (focus motor)"), i2c_cell)
    self.camera_sensor_spin = QSpinBox()
    self.camera_sensor_spin.setRange(0, 3)
    self.camera_sensor_spin.setValue(int(defs.get("sensor_id", 0)))
    self.camera_sensor_spin.valueChanged.connect(lambda v: set_camera_defaults(sensor_id=v))
    sid_cell = QWidget()
    sid_h = QHBoxLayout(sid_cell)
    sid_h.setContentsMargins(0, 0, 0, 0)
    sid_h.addWidget(self.camera_sensor_spin)
    sid_h.addStretch()
    cam_form2.addRow(form_label("CSI sensor-id (autofocus)"), sid_cell)
    i2c_hint = QLabel("Match I2C bus to your Jetson port (see docs). i2cset may require root or the i2c group.")
    i2c_hint.setObjectName("CaptionMuted")
    i2c_hint.setWordWrap(True)
    cam_form2.addRow(i2c_hint)
    self.camera_focus_combo = QComboBox()
    self.camera_focus_combo.setView(QListView())
    self.camera_focus_combo.setFixedHeight(40)
    self.camera_focus_combo.setMaximumWidth(200)
    self.camera_focus_combo.addItem("Fixed", "fixed")
    self.camera_focus_combo.addItem("Manual", "manual")
    self.camera_focus_combo.addItem("Auto", "auto")
    fm = defs.get("focus_mode", "fixed")
    idx = {"fixed": 0, "manual": 1, "auto": 2}.get(fm, 0)
    self.camera_focus_combo.setCurrentIndex(idx)
    self.camera_focus_combo.currentIndexChanged.connect(
        lambda: [set_camera_defaults(focus_mode=self.camera_focus_combo.currentData()), self._update_focus_controls_visibility()]
    )
    cam_form2.addRow(form_label("Focus mode (motorized CSI)"), self.camera_focus_combo)
    cdl.addLayout(cam_form2)

    self.camera_focus_slider_label = form_label_sm("Fixed position (0=infinity):")
    fs_host = QWidget()
    fs_wrap = QVBoxLayout(fs_host)
    fs_wrap.setContentsMargins(0, 0, 0, 0)
    fs_wrap.setSpacing(8)
    fs_wrap.addWidget(self.camera_focus_slider_label)
    self.camera_focus_slider = QSlider(Qt.Orientation.Horizontal)
    self.camera_focus_slider.setRange(0, 1023)
    self.camera_focus_slider.setValue(defs.get("focus_position", 512))
    self.camera_focus_slider.valueChanged.connect(lambda v: set_camera_defaults(focus_position=v))

    slider_row = QHBoxLayout()
    slider_row.addWidget(self.camera_focus_slider)
    slider_row.addStretch()
    fs_wrap.addLayout(slider_row)
    cdl.addWidget(fs_host)

    btn_host = QWidget()
    btn_l = QHBoxLayout(btn_host)
    btn_l.setContentsMargins(0, 0, 0, 0)
    self.camera_focus_apply_btn = QPushButton("Set fixed position")
    self.camera_focus_apply_btn.setObjectName("BtnPrimary")
    self.camera_focus_apply_btn.setMinimumHeight(44)
    self.camera_focus_apply_btn.setMaximumWidth(200)
    self.camera_focus_apply_btn.setCursor(Qt.CursorShape.PointingHandCursor)
    self.camera_focus_apply_btn.clicked.connect(self._apply_focus_csi_camera)
    btn_l.addWidget(self.camera_focus_apply_btn)
    self.camera_sensor_preset_btn = QPushButton("Apply family preset")
    self.camera_sensor_preset_btn.setObjectName("BtnSecondary")
    self.camera_sensor_preset_btn.setMinimumHeight(44)
    self.camera_sensor_preset_btn.clicked.connect(self._apply_camera_sensor_recommendation)
    btn_l.addWidget(self.camera_sensor_preset_btn)
    btn_l.addStretch()
    cdl.addWidget(btn_host)
    self._camera_focus_long_label = QLabel(
        "Fixed: one position at stream start. Manual: slider + button. Auto: runs the configured focuser script. "
        "Stop live CSI preview when possible."
    )
    self._camera_focus_long_label.setObjectName("CaptionMuted")
    self._camera_focus_long_label.setWordWrap(True)
    cdl.addWidget(self._camera_focus_long_label)
    self._camera_sensor_profile_hint = QLabel("")
    self._camera_sensor_profile_hint.setObjectName("CaptionMuted")
    self._camera_sensor_profile_hint.setWordWrap(True)
    cdl.addWidget(self._camera_sensor_profile_hint)
    self._camera_commissioning_hint = QLabel("")
    self._camera_commissioning_hint.setObjectName("CaptionMuted")
    self._camera_commissioning_hint.setWordWrap(True)
    cdl.addWidget(self._camera_commissioning_hint)
    cam_note = QLabel("New streams use these values. Changing AE lock or resolution needs a stream restart.")
    cam_note.setObjectName("CaptionMuted")
    cam_note.setWordWrap(True)
    cdl.addWidget(cam_note)
    cam_row.addWidget(cam_def, 0, Qt.AlignmentFlag.AlignTop)
    cam_row.addStretch(1)
    if engineering_l is not None:
        engineering_l.addLayout(cam_row)
    self._update_aelock_sliders_visibility()
    self._refresh_camera_sensor_profile_hint()
    self._update_focus_controls_visibility()
    self._apply_camera_commissioning_constraints()
    if engineering_l is not None:
        engineering_l.addWidget(hairline())

    station_summary_card = QFrame()
    station_summary_card.setObjectName("SettingsSummaryCard")
    station_summary_l = QVBoxLayout(station_summary_card)
    station_summary_l.setContentsMargins(20, 18, 20, 18)
    station_summary_l.setSpacing(10)
    station_summary_title = QLabel("Runtime Summary")
    station_summary_title.setObjectName("SectionHeading")
    station_summary_l.addWidget(station_summary_title)
    station_summary_hint = QLabel(
        "This page should only contain runtime endpoint, camera source, and hardware I/O. "
        "For model, recipe, threshold, and package changes use Models & Workspaces."
    )
    station_summary_hint.setObjectName("CaptionMuted")
    station_summary_hint.setWordWrap(True)
    station_summary_l.addWidget(station_summary_hint)
    self._settings_station_snapshot = QLabel("")
    self._settings_station_snapshot.setObjectName("CaptionMuted")
    self._settings_station_snapshot.setWordWrap(True)
    station_summary_l.addWidget(self._settings_station_snapshot)
    station_summary_actions = QHBoxLayout()
    station_summary_actions.setSpacing(10)
    open_models_btn = QPushButton("Open Models & Workspaces")
    open_models_btn.setObjectName("BtnSecondary")
    open_models_btn.setFixedHeight(34)
    open_models_btn.clicked.connect(lambda: self.switch(2))
    station_summary_actions.addWidget(open_models_btn)
    open_detection_btn = QPushButton("Open Inspection")
    open_detection_btn.setObjectName("ShellBtn")
    open_detection_btn.setFixedHeight(34)
    open_detection_btn.clicked.connect(lambda: self.switch(1))
    station_summary_actions.addWidget(open_detection_btn)
    station_summary_actions.addStretch(1)
    station_summary_l.addLayout(station_summary_actions)
    station_l.addWidget(station_summary_card)

    station_l.addWidget(settings_title("Inspection runtime"))

    station_profile_card = QFrame()
    station_profile_card.setObjectName("InfoCard")
    station_profile_card.setMaximumWidth(1180)
    station_profile_l = QVBoxLayout(station_profile_card)
    station_profile_l.setContentsMargins(25, 25, 25, 25)
    station_profile_l.setSpacing(16)

    station_profile_hint = QLabel(
        "Configure the production runtime identity and endpoint operators use across the line."
    )
    station_profile_hint.setObjectName("CaptionMuted")
    station_profile_hint.setWordWrap(True)
    station_profile_l.addWidget(station_profile_hint)

    def _mk_settings_combo(maxw=360):
        c = QComboBox()
        c.setView(QListView())
        c.setFixedHeight(40)
        c.setMaximumWidth(maxw)
        return c

    self._inspection_camera_name_input = QLineEdit()
    self._inspection_camera_name_input.setPlaceholderText("Runtime name")
    self._inspection_camera_name_input.setMinimumHeight(40)

    self._inspection_board_combo = _mk_settings_combo(420)
    for board in jetson_board_catalog():
        self._inspection_board_combo.addItem(board.get("label") or board.get("id") or "Jetson", board.get("id"))

    self._inspection_backend_combo = _mk_settings_combo(240)
    self._inspection_backend_combo.addItem("Mock output", "mock")
    self._inspection_backend_combo.addItem("Jetson.GPIO", "jetson_gpio")

    self._inspection_trigger_mode_combo = _mk_settings_combo(260)
    self._inspection_trigger_mode_combo.addItem("Manual trigger", "manual")
    self._inspection_trigger_mode_combo.addItem("Input pin trigger", "input_pin")
    self._inspection_trigger_mode_combo.addItem("Continuous preview only", "continuous")

    self._inspection_runtime_host_input = QLineEdit()
    self._inspection_runtime_host_input.setPlaceholderText("127.0.0.1 or ZeroTier host")
    self._inspection_runtime_host_input.setMinimumHeight(40)

    self._inspection_active_level_combo = _mk_settings_combo(220)
    self._inspection_active_level_combo.addItem("Active HIGH", "high")
    self._inspection_active_level_combo.addItem("Active LOW", "low")

    self._inspection_runtime_port_spin = QSpinBox()
    self._inspection_runtime_port_spin.setRange(1024, 65535)
    self._inspection_runtime_port_spin.setFixedHeight(40)
    self._inspection_runtime_port_spin.setMaximumWidth(180)

    self._inspection_camera_backend_combo = _mk_settings_combo(320)
    self._inspection_camera_backend_combo.addItem("Jetson CSI (Argus)", "jetson_csi_argus")
    self._inspection_camera_backend_combo.addItem("OpenCV device", "opencv_device")
    self._inspection_camera_backend_combo.addItem("Image file (test)", "image_file")
    self._inspection_camera_backend_combo.addItem("Video file (test)", "video_file")
    self._inspection_camera_backend_combo.addItem("Mock frame", "mock_frame")
    self._inspection_camera_model_combo = _mk_settings_combo(320)
    for key, info in csi_sensor_profiles().items():
        self._inspection_camera_model_combo.addItem(info.get("label") or key, key)
    self._inspection_camera_focuser_combo = _mk_settings_combo(360)
    for key, info in focuser_profiles().items():
        self._inspection_camera_focuser_combo.addItem(info.get("label") or key, key)

    def _mk_runtime_spin(minimum, maximum, value=None, step=1, maxw=180):
        s = QSpinBox()
        s.setRange(minimum, maximum)
        s.setSingleStep(step)
        s.setFixedHeight(40)
        s.setMaximumWidth(maxw)
        if value is not None:
            s.setValue(value)
        return s

    self._inspection_camera_sensor_spin = _mk_runtime_spin(0, 7, 0)
    self._inspection_camera_device_spin = _mk_runtime_spin(0, 15, 0)
    self._inspection_camera_width_spin = _mk_runtime_spin(320, 7680, 1920, step=16)
    self._inspection_camera_height_spin = _mk_runtime_spin(240, 4320, 1080, step=16)
    self._inspection_camera_fps_spin = _mk_runtime_spin(1, 120, 30)
    self._inspection_camera_burst_spin = _mk_runtime_spin(1, 9, 3)
    self._inspection_camera_source_input = QLineEdit()
    self._inspection_camera_source_input.setPlaceholderText("/path/to/test-image.jpg or video.mp4")
    self._inspection_camera_source_input.setMinimumHeight(40)

    self._inspection_pass_pin_combo = _mk_settings_combo(420)
    self._inspection_fail_pin_combo = _mk_settings_combo(420)
    self._inspection_fault_pin_combo = _mk_settings_combo(420)
    self._inspection_busy_pin_combo = _mk_settings_combo(420)
    self._inspection_trigger_pin_combo = _mk_settings_combo(420)

    gpio_enable_cell = QWidget()
    gpio_enable_l = QHBoxLayout(gpio_enable_cell)
    gpio_enable_l.setContentsMargins(0, 0, 0, 0)
    self._inspection_gpio_enable_switch = ToggleSwitch()
    gpio_enable_l.addWidget(self._inspection_gpio_enable_switch)
    gpio_enable_l.addStretch()

    runtime_form = QFormLayout()
    runtime_form.setSpacing(14)
    runtime_form.setHorizontalSpacing(16)
    runtime_form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    runtime_form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    runtime_form.addRow(_lockable_form_label("Camera name", "_inspection_camera_name_input"), self._inspection_camera_name_input)
    runtime_form.addRow(_lockable_form_label("Runtime board profile", "_inspection_board_combo"), self._inspection_board_combo)
    runtime_form.addRow(_lockable_form_label("Output backend", "_inspection_backend_combo"), self._inspection_backend_combo)
    runtime_form.addRow(_lockable_form_label("Trigger mode", "_inspection_trigger_mode_combo"), self._inspection_trigger_mode_combo)
    runtime_form.addRow(_lockable_form_label("Runtime host", "_inspection_runtime_host_input"), self._inspection_runtime_host_input)
    runtime_form.addRow(_lockable_form_label("Runtime port", "_inspection_runtime_port_spin"), self._inspection_runtime_port_spin)
    station_profile_l.addLayout(runtime_form)
    station_l.addWidget(station_profile_card)

    station_l.addWidget(settings_title("Camera source"))
    camera_source_card = QFrame()
    camera_source_card.setObjectName("InfoCard")
    camera_source_card.setMaximumWidth(1180)
    camera_source_l = QVBoxLayout(camera_source_card)
    camera_source_l.setContentsMargins(25, 25, 25, 25)
    camera_source_l.setSpacing(16)

    camera_source_hint = QLabel(
        "Set the runtime capture source and validation metadata. Sensor family and focus actuator are commissioning fields, not daily operator controls."
    )
    camera_source_hint.setObjectName("CaptionMuted")
    camera_source_hint.setWordWrap(True)
    camera_source_l.addWidget(camera_source_hint)

    camera_form = QFormLayout()
    camera_form.setSpacing(14)
    camera_form.setHorizontalSpacing(16)
    camera_form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    camera_form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    camera_form.addRow(_lockable_form_label("Capture backend", "_inspection_camera_backend_combo"), self._inspection_camera_backend_combo)
    camera_form.addRow(_lockable_form_label("CSI sensor family", "_inspection_camera_model_combo"), self._inspection_camera_model_combo)
    camera_form.addRow(_lockable_form_label("Focus actuator", "_inspection_camera_focuser_combo"), self._inspection_camera_focuser_combo)
    camera_form.addRow(_lockable_form_label("CSI sensor id", "_inspection_camera_sensor_spin"), self._inspection_camera_sensor_spin)
    camera_form.addRow(_lockable_form_label("OpenCV device index", "_inspection_camera_device_spin"), self._inspection_camera_device_spin)
    camera_form.addRow(_lockable_form_label("Capture width", "_inspection_camera_width_spin"), self._inspection_camera_width_spin)
    camera_form.addRow(_lockable_form_label("Capture height", "_inspection_camera_height_spin"), self._inspection_camera_height_spin)
    camera_form.addRow(_lockable_form_label("Frame rate", "_inspection_camera_fps_spin"), self._inspection_camera_fps_spin)
    camera_form.addRow(_lockable_form_label("Burst frames", "_inspection_camera_burst_spin"), self._inspection_camera_burst_spin)
    camera_form.addRow(_lockable_form_label("Image/video path", "_inspection_camera_source_input"), self._inspection_camera_source_input)
    camera_source_l.addLayout(camera_form)

    inspection_camera_btn_row = QHBoxLayout()
    inspection_camera_btn_row.setSpacing(10)
    self._inspection_camera_apply_preset_btn = QPushButton("Apply family preset")
    self._inspection_camera_apply_preset_btn.setObjectName("BtnSecondary")
    self._inspection_camera_apply_preset_btn.setFixedHeight(34)
    self._inspection_camera_apply_preset_btn.clicked.connect(self._apply_inspection_camera_recommendation)
    inspection_camera_btn_row.addWidget(self._inspection_camera_apply_preset_btn)
    inspection_camera_btn_row.addStretch(1)
    camera_source_l.addLayout(inspection_camera_btn_row)

    self._inspection_camera_profile_hint = QLabel("")
    self._inspection_camera_profile_hint.setObjectName("CaptionMuted")
    self._inspection_camera_profile_hint.setWordWrap(True)
    camera_source_l.addWidget(self._inspection_camera_profile_hint)
    self._inspection_runtime_sensor_hint = QLabel("")
    self._inspection_runtime_sensor_hint.setObjectName("CaptionMuted")
    self._inspection_runtime_sensor_hint.setWordWrap(True)
    camera_source_l.addWidget(self._inspection_runtime_sensor_hint)

    camera_hint = QLabel(
        "Sensor family is commissioning metadata only. Focus, zoom, and aperture depend on the exact module SKU and lens package. "
        "For production operators, keep these values locked and let the Jetson runtime report the installed hardware."
    )
    camera_hint.setObjectName("CaptionMuted")
    camera_hint.setWordWrap(True)
    camera_source_l.addWidget(camera_hint)
    station_l.addWidget(camera_source_card)

    station_l.addWidget(settings_title("Trigger & outputs"))
    gpio_card = QFrame()
    gpio_card.setObjectName("InfoCard")
    gpio_card.setMaximumWidth(1180)
    gpio_l = QVBoxLayout(gpio_card)
    gpio_l.setContentsMargins(25, 25, 25, 25)
    gpio_l.setSpacing(16)

    gpio_hint = QLabel(
        "Map the foot pedal or sensor input and the PASS / FAIL / FAULT / BUSY indicators for the runtime node."
    )
    gpio_hint.setObjectName("CaptionMuted")
    gpio_hint.setWordWrap(True)
    gpio_l.addWidget(gpio_hint)

    gpio_form = QFormLayout()
    gpio_form.setSpacing(14)
    gpio_form.setHorizontalSpacing(16)
    gpio_form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    gpio_form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    gpio_form.addRow(_lockable_form_label("Enable Hardware Lights (LED)", "_inspection_gpio_enable_switch"), gpio_enable_cell)
    gpio_l.addLayout(gpio_form)

    self._gpio_details_widget = QWidget()
    gpio_details_form = QFormLayout(self._gpio_details_widget)
    gpio_details_form.setSpacing(14)
    gpio_details_form.setHorizontalSpacing(16)
    gpio_details_form.setLabelAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    gpio_details_form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
    gpio_details_form.setContentsMargins(10, 0, 0, 0)

    gpio_details_form.addRow(_lockable_form_label("Active level", "_inspection_active_level_combo"), self._inspection_active_level_combo)
    gpio_details_form.addRow(_lockable_form_label("Green (PASS) Light Pin", "_inspection_pass_pin_combo"), self._inspection_pass_pin_combo)
    gpio_details_form.addRow(_lockable_form_label("Red (FAIL) Light Pin", "_inspection_fail_pin_combo"), self._inspection_fail_pin_combo)
    gpio_details_form.addRow(_lockable_form_label("Error Light Pin", "_inspection_fault_pin_combo"), self._inspection_fault_pin_combo)
    gpio_details_form.addRow(_lockable_form_label("Processing Light Pin", "_inspection_busy_pin_combo"), self._inspection_busy_pin_combo)
    gpio_details_form.addRow(_lockable_form_label("Foot Pedal / Sensor Pin", "_inspection_trigger_pin_combo"), self._inspection_trigger_pin_combo)
    gpio_l.addWidget(self._gpio_details_widget)

    self._gpio_details_widget.setVisible(False)
    self._inspection_gpio_enable_switch.toggled.connect(self._gpio_details_widget.setVisible)

    self._inspection_pin_summary = QLabel("")
    self._inspection_pin_summary.setObjectName("CaptionMuted")
    self._inspection_pin_summary.setWordWrap(True)
    gpio_l.addWidget(self._inspection_pin_summary)
    station_l.addWidget(gpio_card)

    system_l.addWidget(settings_title("Local services"))
    system_l.addWidget(sys_info)

    system_l.addWidget(settings_title("Hardware summary"))
    hw = QFrame()
    hw.setObjectName("InfoCard")
    hl = QGridLayout(hw)
    hl.setContentsMargins(25, 25, 25, 25)
    hl.setSpacing(30)
    inf = [("Architecture", platform.machine()), ("CPU cores", str(psutil.cpu_count())), ("OS", platform.system()), ("Graphics", get_gpu_info())]
    for i, (k, v) in enumerate(inf):
        lv = QVBoxLayout()
        lk = QLabel(k)
        lk.setObjectName("CaptionMutedSm")
        lv.addWidget(lk)
        vv = QLabel(v)
        vv.setObjectName("HWValue")
        lv.addWidget(vv)
        hl.addLayout(lv, 0, i)
    system_l.addWidget(hw)

    system_l.addWidget(settings_title("Live system metrics"))
    metrics_card = QFrame()
    metrics_card.setObjectName("InfoCard")
    ml = QHBoxLayout(metrics_card)
    ml.setSpacing(28)
    ml.setContentsMargins(28, 28, 28, 28)
    self.charts = [DonutChart("CPU", "#EF4444"), DonutChart("RAM", "#10B981"), DonutChart("Disk", "#3B82F6"), DonutChart("GPU", "#8B5CF6")]
    for ch in self.charts:
        ml.addWidget(ch)
    system_l.addWidget(metrics_card)

    self._inspection_camera_name_input.textChanged.connect(lambda _t: self._save_inspection_profile_from_ui())
    self._inspection_backend_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_trigger_mode_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_runtime_host_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_active_level_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_runtime_port_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_backend_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_camera_model_combo.currentIndexChanged.connect(self._on_inspection_camera_sensor_model_changed)
    self._inspection_camera_focuser_combo.currentIndexChanged.connect(lambda _i: [self._save_inspection_profile_from_ui(), self._refresh_inspection_camera_profile_hint()])
    self._inspection_camera_sensor_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_device_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_width_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_height_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_fps_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_burst_spin.valueChanged.connect(lambda _v: self._save_inspection_profile_from_ui())
    self._inspection_camera_source_input.editingFinished.connect(self._save_inspection_profile_from_ui)
    self._inspection_gpio_enable_switch.toggled.connect(lambda _c: self._save_inspection_profile_from_ui())
    self._inspection_pass_pin_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_fail_pin_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_fault_pin_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_busy_pin_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_trigger_pin_combo.currentIndexChanged.connect(lambda _i: self._save_inspection_profile_from_ui())
    self._inspection_board_combo.currentIndexChanged.connect(self._on_inspection_board_changed)

    self._sync_inspection_profile_ui()
    self._apply_camera_commissioning_constraints()
    self._refresh_settings_hub()
    station_l.addWidget(hairline())

    ih = QHBoxLayout()
    ih.addWidget(settings_title("Image repository"))
    ih.addStretch()
    ih.addWidget(make_icon_refresh_button(self.refresh_images, "Refresh Docker images"))
    if not getattr(self, "_production_mode", False):
        engineering_l.addLayout(ih)

    ic = QFrame()
    ic.setObjectName("InfoCard")
    il = QVBoxLayout(ic)
    il.setContentsMargins(20, 20, 20, 20)
    il.setSpacing(10)
    hl = QHBoxLayout()
    rep_h = QLabel("REPOSITORY")
    rep_h.setObjectName("CaptionMutedSm")
    sz_h = QLabel("SIZE")
    sz_h.setObjectName("CaptionMutedSm")
    sz_h.setStyleSheet("margin-right: 60px;")
    hl.addWidget(rep_h)
    hl.addStretch()
    hl.addWidget(sz_h)
    il.addLayout(hl)
    il.addWidget(hairline())
    self.img_list_layout = QVBoxLayout()
    self.img_list_layout.setSpacing(8)
    il.addLayout(self.img_list_layout)
    self.refresh_images()
    if not getattr(self, "_production_mode", False):
        engineering_l.addWidget(ic)
    for target in (station_l, network_l, system_l, maintenance_l, engineering_l):
        if target is not None:
            target.addStretch()
    if hasattr(self, "_apply_settings_role_mode"):
        self._apply_settings_role_mode()
    return root
